votee_app_rest_content:
  resource: "@VoteeAppBundle/Controller/Rest/BoardController.php"
  type: rest
  prefix: api/v1
  name_prefix: api_v1_votee_app_

votee_app_rest_vote:
  resource: "@VoteeAppBundle/Controller/Rest/VoteController.php"
  type: rest
  prefix: api/v1
  name_prefix: api_v1_votee_app_
