votee_app:
  resource: "@VoteeAppBundle/Resources/config/routing/routing.yml"
  prefix: /{_locale}
  requirements:
    _locale: %locales%
  defaults:
    _locale: %locale%

votee_app_default_locale:
  path: /{url}
  requirements:
    url: "[^(%locales%)]?.*"
  defaults:
    _controller: VoteeAppBundle:Default:defaultLocaleRedirect

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
